version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=matbaza
      - POSTGRES_USER=matbaza
      - POSTGRES_PASSWORD=M6K99qZcuyQKXJyFgozIG50H6joZ3JRyxXZMfJtXRU6p08nnv4
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "80:8000"
    depends_on:
      - db